<a href="https://colab.research.google.com/github/dikshap07/ML-Algorithms/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#print zeros two rows 3 columns:

zero_array = np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#eye()

arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.eye(4,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
#diag() -> creates a diagonal square matrix 
b = np.diag([1,2,5])
print(b)

[[1 0 0]
 [0 2 0]
 [0 0 5]]


In [ ]:
#Print Range Between 1 To 15 and show 4 integers random numbers

new = np.random.randint(1,15,4)
print(new)

[ 1  6 12  8  5]


In [ ]:
#Print Range Between 1 To 100 and show 4 integers random numbers
new_ = np.random.randint(1,100,4)
print(new_)
rand_arr3 = np.random.randint(1,100,4)
print('\n random number from 1 to 100' ,rand_arr3)

[57 68 56 64]

 random number from 1 to 100 [64 13 37 35]


In [ ]:
#Print Range Between random number 2 row and 3 cols integers random numbers

new = np.random.randint([2,3])
print(new)

[1 1]


In [ ]:
rand_arr2 = np.random.randint([2,3])
print('\n random number 2 row and 3 cols ',rand_arr2)


 random number 2 row and 3 cols  [1 2]


In [ ]:
#describe the example of seed() function? and how to use it ? why seed()?

np.random.seed(12)
rand_arr4 = np.random.randint(1,100,20)
print('\nseed() showing same number only : ',rand_arr4)




seed() showing same number only :  [76 28  7  3  4 68 77 49 23 50 53  6 14 90 35 76 75  1 77 14]


In [ ]:
rand_arr4[-1]

14

In [ ]:
a[0][0]

1.0

In [ ]:
b[1][1]

2

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
boo = np.arange(0,100).reshape(10,10)
print(boo)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
#size of array

boo.size

100

In [ ]:
boo.shape

(10, 10)

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
i = np.linspace(0,12,16).reshape(4,4)
print(i)

[[ 0.   0.8  1.6  2.4]
 [ 3.2  4.   4.8  5.6]
 [ 6.4  7.2  8.   8.8]
 [ 9.6 10.4 11.2 12. ]]


In [ ]:
k = np.arange(1,9).reshape(2,4)
print(k)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
k[1,:]

array([5, 6, 7, 8])

In [ ]:
i[1:3,:]

array([[3.2, 4. , 4.8, 5.6],
       [6.4, 7.2, 8. , 8.8]])

In [ ]:
i[3,:]

array([ 9.6, 10.4, 11.2, 12. ])

In [ ]:
i[1:]

array([[ 3.2,  4. ,  4.8,  5.6],
       [ 6.4,  7.2,  8. ,  8.8],
       [ 9.6, 10.4, 11.2, 12. ]])

In [ ]:
i.ravel()

array([ 0. ,  0.8,  1.6,  2.4,  3.2,  4. ,  4.8,  5.6,  6.4,  7.2,  8. ,
        8.8,  9.6, 10.4, 11.2, 12. ])

In [ ]:
num = np.arange(0,16).reshape(4,4)

mask = num > 5
print(num[mask])

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(num[num%2==0])



[ 0  2  4  6  8 10 12 14]


In [ ]:
#num.reshape(4,4)
print(num)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
z = np.concatenate((i,num))

In [ ]:
print(z)

[[ 0.   0.8  1.6  2.4]
 [ 3.2  4.   4.8  5.6]
 [ 6.4  7.2  8.   8.8]
 [ 9.6 10.4 11.2 12. ]
 [ 0.   1.   2.   3. ]
 [ 4.   5.   6.   7. ]
 [ 8.   9.  10.  11. ]
 [12.  13.  14.  15. ]]


In [ ]:
z = np.concatenate((i,num),axis = None)
print(z)

[ 0.   0.8  1.6  2.4  3.2  4.   4.8  5.6  6.4  7.2  8.   8.8  9.6 10.4
 11.2 12.   0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.
 12.  13.  14.  15. ]


In [ ]:
np.sort(z)

array([ 0. ,  0. ,  0.8,  1. ,  1.6,  2. ,  2.4,  3. ,  3.2,  4. ,  4. ,
        4.8,  5. ,  5.6,  6. ,  6.4,  7. ,  7.2,  8. ,  8. ,  8.8,  9. ,
        9.6, 10. , 10.4, 11. , 11.2, 12. , 12. , 13. , 14. , 15. ])

In [ ]:
j = np.multiply(i,num)
print(j)

[[  0.    0.8   3.2   7.2]
 [ 12.8  20.   28.8  39.2]
 [ 51.2  64.8  80.   96.8]
 [115.2 135.2 156.8 180. ]]


In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result=np.multiply(array1,array2)
print('\n result \n',result)


 result 
 [[[ 9 16 21]
  [24 25 24]
  [21 16  9]]]


In [ ]:
#what is the use of append() function with axis=0 ?
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])
c=np.append(a,b,axis=1)
print('\n append function with axis = 0\n ',c)


 append function with axis = 0
  [[ 1  2  3 11 21 31]
 [ 4  5  6 42 52 62]
 [ 7  8  9 73 83 93]]


In [ ]:
np.rint(i)

array([[ 0.,  1.,  2.,  2.],
       [ 3.,  4.,  5.,  6.],
       [ 6.,  7.,  8.,  9.],
       [10., 10., 11., 12.]])

In [ ]:
#replacing element in array satisfying a particular condition without disturbing original array

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#stack two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


In [ ]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.r_[a, b]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.intersect1d(i,num)

array([ 0.,  4.,  8., 12.])

In [ ]:
np.setdiff1d(i,num)

array([ 0.8,  1.6,  2.4,  3.2,  4.8,  5.6,  6.4,  7.2,  8.8,  9.6, 10.4,
       11.2])